//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLModelContainer : DbContext
    {
        public DLModelContainer()
            : base("name=DLModelContainer")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PaymentsSetting> PaymentsSettingSet { get; set; }
        public virtual DbSet<GlobalSetting> GlobalSettingSet { get; set; }
        public virtual DbSet<Operator> OperatorSet { get; set; }
        public virtual DbSet<UsersType> UsersTypeSet { get; set; }
        public virtual DbSet<SingularUser> SingularUserSet { get; set; }
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Airplane> AirplaneSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<Flight> FlightSet { get; set; }
        public virtual DbSet<FlightsElem> FlightsElemSet { get; set; }
        public virtual DbSet<Parachute> ParachuteSet { get; set; }
    }
}
