//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<double> Value { get; set; }
        public bool Camera { get; set; }
        public bool TandemPilot { get; set; }
        public bool TandemPassenger { get; set; }
        public int SpecialType { get; set; }
    
        public virtual User User { get; set; }
        public virtual FlightElement FlightElement { get; set; }
    }
}
