//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TandemOrder
    {
        public int Id { get; set; }
        public System.DateTime SuggestDateTime { get; set; }
    
        public virtual User TandemPilot { get; set; }
        public virtual FlightElement FlightElement { get; set; }
        public virtual User TandemPassenger { get; set; }
    }
}
